spring:
  application:
    name: hhplus-architecture
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:hhplus-sa;MODE=MySQL
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
